# ============================================================
# services/export_service.py
# ============================================================
# STEP 7B: Export Service — CSV & Markdown Generation
#
# This module handles formatting and generating downloadable
# export files from the current tasks DataFrame.
#
# SUPPORTED EXPORTS:
#   1. CSV  — Standard comma-separated task list
#   2. Markdown — Formatted meeting report (.md file)
#
# WHY SEPARATE: Keeps export formatting logic out of app.py
# so the UI only calls one function per export type.
# ============================================================

import pandas as pd
from datetime import datetime, timezone


# ============================================================
# STEP 7B.1: Export Tasks to CSV
# ============================================================
def export_to_csv(tasks_df: pd.DataFrame) -> bytes:
    """
    STEP 7B.1: Convert tasks DataFrame to a UTF-8 CSV bytes object.

    Returns bytes so Streamlit's st.download_button can serve it
    directly as a file download without writing to disk.

    Args:
        tasks_df (pd.DataFrame): Current tasks DataFrame from session state.

    Returns:
        bytes: CSV-encoded bytes of the tasks table.
    """
    # STEP 7B.1.1: Drop internal 'id' column — not needed in exports
    export_df = tasks_df.copy()
    if "id" in export_df.columns:
        export_df = export_df.drop(columns=["id"])

    # STEP 7B.1.2: Rename columns to title case for readability
    export_df.columns = [col.replace("_", " ").title() for col in export_df.columns]

    # STEP 7B.1.3: Convert to CSV string and encode to bytes
    # index=False → don't include row numbers in the CSV
    csv_bytes = export_df.to_csv(index=False).encode("utf-8")

    return csv_bytes


# ============================================================
# STEP 7B.2: Export Full Meeting Report as Markdown
# ============================================================
def export_to_markdown(
    title: str,
    summary: str,
    decisions: str,
    tasks_df: pd.DataFrame
) -> bytes:
    """
    STEP 7B.2: Generate a formatted Markdown meeting report.

    The Markdown file contains the meeting title, summary,
    key decisions, and a formatted task table.
    Compatible with Notion, GitHub wikis, and Obsidian.

    Args:
        title (str): Meeting title from session state.
        summary (str): Meeting summary from session state.
        decisions (str): Key decisions text from session state.
        tasks_df (pd.DataFrame): Current tasks DataFrame.

    Returns:
        bytes: UTF-8 encoded Markdown document bytes.
    """
    # STEP 7B.2.1: Build the Markdown document header
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    md_lines = [
        f"# 📋 {title}",
        f"> Generated by AI Project Manager on {timestamp}",
        "",
        "---",
        "",
        "## 📝 Meeting Summary",
        "",
        summary or "_No summary available._",
        "",
        "---",
        "",
        "## ✅ Key Decisions",
        "",
        decisions or "_No decisions recorded._",
        "",
        "---",
        "",
        "## 📌 Extracted Tasks",
        "",
    ]

    # STEP 7B.2.2: Build the Markdown task table
    if tasks_df.empty:
        md_lines.append("_No tasks extracted._")
    else:
        # Prepare display columns (drop internal id)
        display_df = tasks_df.copy()
        if "id" in display_df.columns:
            display_df = display_df.drop(columns=["id"])

        # Replace empty due_date with "TBD"
        if "due_date" in display_df.columns:
            display_df["due_date"] = display_df["due_date"].replace("", "TBD")
            display_df["due_date"] = display_df["due_date"].fillna("TBD")

        # Write Markdown table header
        headers = ["Task", "Assignee", "Priority", "Due Date", "Status", "Description"]
        cols = ["name", "assignee", "priority", "due_date", "status", "description"]

        md_lines.append("| " + " | ".join(headers) + " |")
        md_lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

        # Write each task as a table row
        for _, row in display_df.iterrows():
            values = [str(row.get(col, "")).replace("|", "\\|") for col in cols]
            md_lines.append("| " + " | ".join(values) + " |")

    # STEP 7B.2.3: Add footer
    md_lines += [
        "",
        "---",
        "",
        "_Report generated by AI Project Manager — Powered by Gemini / Ollama_",
    ]

    # STEP 7B.2.4: Join all lines and encode to bytes
    md_content = "\n".join(md_lines)
    return md_content.encode("utf-8")
